### ISSUE TITLE
Value-Added Enhancement:  A.02 Enter Project Info & E.01 Create Forms and Letters (Client and "Associated" Mailing Addresses)

### ISSUE THREAD

**Issue by AC0192021** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#127]
Both WC and HEL Tools, via A.02, provide users the option to complete data entry concerning Client Mailing Addresses.  This information is archived/saved (text file) by the WC/HEL Tools and accessed/used throughout the workflow to auto-fill map headers, forms, and letters.  

It is my understanding Policy potentially requires not only the direct Client involved in the referral document(s) to be notified, but also all persons associated with the Tract.  While the WC/HEL Tools automatically populate the client involved in the referral documents, there is not a mechanism for all persons associated with the Tract to be auto populated in tool derived client forms (Owner, Operator, Other).

There are numerous instances, where Iowa NRCS Compliance staff members are required to enter additional, associated persons of the Tract.  For example, it is very common for the Compliance Staff member to complete data entry for 8 associations of the tract.

![image](https://github.com/user-attachments/assets/bd5c8781-8c21-43d4-9faf-f4ff2cc96f2d)

I believe a value-added approach to minimize additional user data entry efforts is automation.  I propose this be comparable to what is implemented in the WC Tool code now.  A.01, Create Wetlands Project, connects to the National CLU Service, and amongst many other things, extracts geospatial data from the service and archives these data within C:\Determinations for further use-the same is said about NWI data.  

In the case of Soils data, the Tool connects to Soil Data Access (SDA) to extract spatial and tabular information based on AOI minimum bounding coordinates and creates multiple layers for future use.

I propose we seek similar extraction methods for all associated persons of the Tract using the FSA authoritative database.  This is not something Iowa NRCS GIS can achieve due to accessibility/credential issues, rather this should be targeted and deployed at the National Level.  

The proposed extraction should take place preceding WC Tool E.01 Create Forms and Letters, and HEL Tool B.03 Create Form, Letter, Report.  This allows the extraction to be as current as possible and minimizes downstream effects of tract association errors of omission and commission-the risk of omitting an associated person or the risk of including an association, in which case, both errors potentially impact policy.

This value-added approach benefits all users of the WC and HEL Tools, not simply Iowa.  This increases the efficiency and effectiveness of the staff member and agency tools, and would reduce redundant data entry, keep administrative data entry at the FSA level, reduce errors/liabilities, etc.

**Comment by Ripper-del-pixel** [comment]
I would like to express that this is a great idea which I would like to see the Natural Resources Conservation Service (NRCS) implement as currently proposed, if they did not have to rely on another agency: Farm Service Agency (FSA).  The FSA database is unreliable at times because the FSA does not differentiate between participant and non-participant affiliated parties.  The NRCS National Wetland Conservation (WC) Tool would generate automatically populated forms for each party in the FSA database for that tract, and the NRCS would mail them all out, eventually resulting in disclosures prohibited under Title 7, Section 8791, after non-participants who are listed in the FSA database get forms which have protected information on them.  If concerns about the FSA database limitations presents as incredible, just look at how many acreages (with non-participants) the FSA can't be bothered to take the time to deactivate after it gets broken off and sold, which the NRCS gets assigned to monitor during status reviews.  A solution which requires the NRCS to manually select automatically imported addresses from a dropdown list (like the Lesson Plans/User Guide shows for B.03 [Optional] Export Reference Maps) might be more viable.

**Comment by CEM-NRCS** [comment]
In review with National compliance tool leads, the focus of this innovation will be pushed towards the WDT development being integrated with CD, and the ArcGIS Pro tool is effectively moving into maintenance mode to sustain operations as is, without major enhancements, so as to not duplicate development investments.
