### ISSUE TITLE
Tool D 14 - Create Forms and Letters (several issues)

### ISSUE THREAD

**Issue by DGehring-KY** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#27]
1 - On the WC letter that is generated, you should have the Farm Number listed as well as the Tract number. All correspondence with landowners includes Farm and Tract numbers, as they have a tendency to change over time due to reconstitutions by FSA.  The Farm Number is listed on the 026-WC, and should also be listed on the letter as well.

2 - The generated 026-WC looks very different than the official 026-WC that we started using last year (Sept 2020). Some formatting might be needed to look more like the official form.  In the Remarks section, we are supposed to enter text describing the PJW that are on maps (if applicable).  That is not possible with this version.  If a PJW is digitized, then it should have this statement in the Remarks section.

Remarks with PJW should say: "Areas identified as Potential Jurisdictional Waters (PJW) are not subject to the Food Security Act but are potentially subject to the Clean Water Act. You should contact the U.S. Army Corps of Engineers local district office prior to performing work in areas which may be subject to the Clean Water Act. Areas identified as PJW are for informational purposes only and are not appealable to USDA. Additional areas, not identified by NRCS, might also be subject to the Clean Water Act."

3 - Address of Landowner has an error when it creates it on the WC letter and 026-WC.  When nothing is listed on the second address line (no apartment, P.O. Box, etc..), then it adds a "NA" after the street address.  Can this be corrected or removed when not used?

4 - 026-WC has no signature line listed. When it generates, it has the header of the Designated Conservationist, but no line to sign on. It would be nice to have an actual line to sign, or a box to enter a digital signature.  It would be nice to list the date on a line as well.

5 - In KY, when a landowner does not agree with the determination, then they are asked to contact the State Soil Scientist who is responsible for Wetland Compliance in the state. In the generated WC Letter, it says to contact in writing the local field office listed at the top of the letter to dispute a determination. We are removing the "middle man" (Field office staff) and going straight to the compliance officer in the state who deals with reconsiderations. Is there a way to list that in the letter instead of the field office text?

**Comment by CEM-NRCS** [comment]
- Farm Number is not considered to be a required element of the letter by the policy team involved in tool development.
- Formatting updated on the 026 Form prior to final release. Extending PJW statements with details is possible because the output generates in Word, which is freely editable. The standard PJW language that you've highlighted in this note is programmed into the final release of the tool.
- The "NA" when the 2nd address line isn't used has been corrected and is no longer appearing on the forms and letter.
- The box beneath item number 10 is the intended location for signature on the form. This can be a digital signature after converting to PDF.  The box is adjustable in size as part of an editable Word doc when the form generates.
- States can edit the template letter in R as needed and instructions are in the final release documentation for how to do this.  States are expected to customize the tools within their state and then deploy the custom version to their state's users.  Further questions for how to do this can be directed to Edwin Muniz.  For any concerns about how to locally customize the language of the letter within policy, please contact Jason Outlaw.  Also, the final tool updated the return address methodology to allow users to select an office from a pick list developed by the state to further support custom options and local operational differences.
