### ISSUE TITLE
Tool A.01 i 

### ISSUE THREAD

**Issue by jeff-ARSS** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#32]
cannot create the project
![Tool A  01 i](https://user-images.githubusercontent.com/87143736/125633512-4844e569-d347-4875-b550-ec9f920a14df.PNG)

**Comment by CEM-NRCS** [comment]
Test run of tracts in Lafayette WI are successful in the release version. Possible additional error checks are now in place to track down this problem before getting to this message (e.g., not signed-in, timed-out sign-in, failed CLU download, etc...).

**Comment by CEM-NRCS** [comment]
Also, on re-run, tests found no CLU fields associated with Tract 12 in Lafayette County and a more suitable error message to relay that information appeared. It's possible that Tract 12 is actually administered by a different county or it was reconned out of existence since the report of this issue. This tool should be set to the administrative county for the tract when running it.
