### ISSUE TITLE
Tool B. 07 - editing Site_Sampling_Units

### ISSUE THREAD

**Issue by lmblackburn** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#34]
I can't seem to enter the associated ROP Number in the Site Sampling Units layer.  I got one of the rows to accept an entry but all of the other rows convert back to <NULL> right after I type the corresponding Associated ROP Number and hit enter.  Every time these values are changed back to <NULL>.  Not sure what's going on.

**Comment by lmblackburn** [comment]
This layer wouldn't allow editing.  I followed a suggestion on another issue and just closed the map pane and reopened it and now I can edit again.  I had to do this a few times to be able to enter all the ROP numbers

**Comment by CEM-NRCS** [comment]
Yeah. This is the unusual editing issue that seems to tie the table up in the script and not release it because Pro doesn't have a RefreshActiveView arcpy command like ArcMap did. The close-reopen is one workaround, and Gregg also suggests removing the layer and then undoing the "remove". I'm also looking at a possible tool to "repair project layers", or just doing away with Topology checks in the validate tools and checking attributes only to try to prevent thins.

**Comment by CEM-NRCS** [comment]
Locks were tied to attribute rules and layer management during processing. Implemented some changes to reduce the instances of this issue.
