### ISSUE TITLE
Appendix D instructions

### ISSUE THREAD

**Issue by DGehring-KY** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#42]
Step 3 c. says that there are two scripts to run in R Studio. After reading lines 12-16, it says to run the script lines after the # sign, which there are 5 of them. I assume to run all five scripts.  This is very confusing and unclear. If we are to run all FIVE scripts, then you should add those line numbers in the instructions and change the wording "two scripts" to "five scripts".  Please make this more clear as this is confusing in the present wording.

Then in Step 3 d. when you close R Studio, it asks if you should save the image or not? I have no idea if that is a Yes or No answer. I chose No as a guess.  Please specify in the instructions.

**Comment by lmblackburn** [comment]
I think I had an issue with this step due to my migration to one drive just yesterday.  It appears that the files that the script is trying to delete are not there because they didn't get redirected w/ the one drive push.  Here's my error from running the first line of code: 

Error in readRDS(pfile) : error reading from connection
In addition: Warning message:
In readRDS(pfile) : error reading the file
> #Unistall arcgisbinding package
> remove.packages(arcgisbinding)
Error in remove.packages : object 'arcgisbinding' not found
There were 50 or more warnings (use warnings() to see the first 50)
Error in readRDS(pfile) : error reading from connection
In addition: Warning message:
In readRDS(pfile) : error reading the file


And here's the message from OneDrive -  RStudion R session is downloading from OneDrive-USDA
This window keeps popping up and it dosen't appear that the code is progressing in R
![image](https://user-images.githubusercontent.com/87446239/128888577-aef17b40-a583-460a-9415-4df841ba24c7.png)
