### ISSUE TITLE
Test2 A6 Legend and SSURGO date

### ISSUE THREAD

**Issue by DGehring-KY** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#44]
There needs to be instructions on how to remove items from the legend from showing up on the maps for layers that were manually entered on the State/County Template setup. All the layers that I added now show up on the maps which I don't want (roads, hydrography, Aerial imagery, Topo, etc.). This just clutters up the legend with junk and shoves the important stuff off of it as the legend box is not large enough to hold it all.

I did uncheck the boxes for the layers that I didn't want shown on the Location Map Layout under Legend, but that only shut them off for the first map that was created and every subsequent map made had everything turned on again. Is there a way to turn them off for all maps created?

On the maps with Soils data, a SSURGO date is populated.  Unfortunately, it is a copy of the Map Creation Date.  This is completely redundant and not needed.  It would be very nice if the SSURGO date was actually the Version Date.  A soil survey version number for the SSURGO would also be nice to include.

Replace the SSURGO date on this:
![image](https://user-images.githubusercontent.com/87146957/127703489-be032670-cbd8-4c35-b590-0770241ec90e.png)

With this:
![image](https://user-images.githubusercontent.com/87146957/127703551-9e507654-e872-418a-a1f3-faaa42b92876.png)
  
If that is not acceptable, I would just leave the SSURGO date off completely then.

**Comment by DMillerAK** [comment]
Since this is similar to the legend/SSURGO item - Adding it here.  Please also include instructions on changing scale bars and/or other legend items.  Right now the scale bar defaulted is not useable - runs off the page.   Also don't need to see the RGB boxes of color imagery in the determination map legend
![image](https://user-images.githubusercontent.com/86498435/129276866-c5ec72b5-b1df-45ee-8392-cf3929a0a29e.png)
![image](https://user-images.githubusercontent.com/86498435/129276958-5387d1ea-28bf-4562-b2c1-ea44fc0041b5.png)

**Comment by CEM-NRCS** [comment]
Legend properties of installed layouts were updated to not show additional layers not visible and a function box was created to specifically show the active imagery layer outside of the legend. Layer properties at run time of operational layers were updated to not show features from the legend not present in the extent. Additional layers added by a state are out of scope of automation and must be configured by the state specialist or the user to add this property (don't display features not present in the extent in the legend).
