### ISSUE TITLE
Test2 B9 

### ISSUE THREAD

**Issue by DGehring-KY** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#45]
After running scenario 1 with the reference points turned on and drainage lines turned on, it displayed the reference points and drainage lines that were digitized on the output, even though the check boxes in the geoprocessing parameters were not checked.  It gave the exact same output as if the Site Reference Point box and Drainage Lines boxes were checked in the parameters box.  Something is not working correctly on this yet.

**Comment by MatthewBaltes** [comment]
I saw this too.
![image](https://user-images.githubusercontent.com/88503273/128526569-5ba3da05-6246-421e-8d71-2d659bcb3313.png)

**Comment by lmblackburn** [comment]
The map PDF was created but the map pane was empty.  Here's the parameters:
![image](https://user-images.githubusercontent.com/87446239/129028962-4db4ea78-ad42-4035-8550-0132be48d589.png)
And the map:
![image](https://user-images.githubusercontent.com/87446239/129029019-c0b04f13-f797-4a55-9585-5a180742d8f5.png)

**Comment by CEM-NRCS** [comment]
Drainage Lines code updated to only display if enabled in user parameters:
![image](https://user-images.githubusercontent.com/47194402/181090471-84005304-8efe-4251-a825-7777a6af7840.png)

Manual pan and zoom requires going to the layout and manually activating the map frame to pan and zoom to a desired extent.

Using the Zoom to a Layer option is suggested for the Site_CLU layer only, as of release. This is due to issues with Pro not updating the default extent of newly created layers in some cases, even when we have code explicitly calling for all layers to have their extents refreshed to the maximum extent of stored features.
