### ISSUE TITLE
Test 2 C13

### ISSUE THREAD

**Issue by DGehring-KY** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#46]
Once the tool ran, the output looks OK on screen. But when you print the map off, the green boundary of the Site_CWD or the Site_CLU_CWD is almost invisible when it is located in wooded areas. You need to choose a different color as over 90% of the wetlands we do are in wooded areas and the map will be worthless if the landowner cannot see where the boundaries are located.

**Comment by MatthewBaltes** [comment]
Also, the Site PJW displays on map and legend whether you select that option or not, since it is on in the TOC.

**Comment by MelHann213** [comment]
Map Layout problem in Zoom to Layer, Site_CLU_CWD.
[C13error_Determination_Map_zoomtosite_CLU_CWD.pdf](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/files/6983426/C13error_Determination_Map_zoomtosite_CLU_CWD.pdf)

**Comment by MelHann213** [comment]
Determination map product for Site_CLU_CWD is very confusing. I would suggest
[Site_CLU_cwd_Determination_Map.pdf](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/files/6983457/Site_CLU_cwd_Determination_Map.pdf)
 a 3rd map layout option - the green Site_CWD with a yellow Site_CLU overlay.

**Comment by CEM-NRCS** [comment]
Appearance of layers can be customized prior to export. If customizing appearance, unless otherwise needed (e.g. draft base map to take to the field), try to not to customize colors until workflow is complete and you are ready to produce finished products. This is because to avoid some file locks, some operational layers had to be removed/re-added to the map frame.
