### ISSUE TITLE
Acreage Label Mismatch

### ISSUE THREAD

**Issue by ryan-nagelkirk** [USDA-NRCS/Wetland-Tools---ArcGIS-Pro#82]
The acreage label in the Determination map is rounded, while the number in the Certified Wetland Determination letter is not. The difference is small, but we're submitting this in case there are any potential legal ramifications. In the attached example, the acreage was 54.765 then rounded to 54.77 in the map label and likely trimmed to 54.76 in the letter. We're not sure if the number is supposed to be rounded or not per policy, but were more concerned about the numbers matching one way or the other. 
[Rounded Acreage Label.docx](https://github.com/USDA-NRCS/Wetland-Tools---ArcGIS-Pro/files/10872793/Rounded.Acreage.Label.docx)

**Comment by CEM-NRCS** [comment]
This is a known issue that was accepted by policy product sponsors during development as a result of two alternate mapping workflows in the tool - with fields and without fields.  Calculating acres and rounding at the CWD level, and then subdividing by field and calculating/rounding acres again to be summarized at the CLUCWD level results in this discrepancy. The option to truncate instead to avoid this discrepancy was declined (e.g. a 0.005 to 0.009 acres label would come out as 0.00 with truncation on the form, instead of 0.01 with rounding).

To mitigate this issue and force maps to match 026 acres, incorporate field lines into the Sampling Unit layer when running Create Base Map Layers. These field boundaries will carry through the Sampling Unit and CWD layers. You will get 8 fields (in your example) for the CWD layer with acres that round (and subsequently intersect, recalculate, and re-round) to always match between the map and the form. You would also have a CWD map with 8 NW labels (1 per field).

Alternately, manually edit the form after it is created to match the CWD map if the CWD layer & map are going to be produced without field lines integrated throughout (during the base map creation step).
